version: '3'

volumes:
  postgres_data: {}
  mongo_data: {}
  kafka_data: {}

services:
  auth_service:
    build:
      context: .
      dockerfile: ./compose/auth/Dockerfile
    container_name: ig_auth_service
    env_file:
      - ./compose/envs/auth.env
    volumes:
      - ./services/auth:/app
    ports:
      - '8001:8000'
    networks:
      - ig_network
    depends_on:
      - postgres
      - kafka
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.6
    container_name: ig_kafka
    env_file:
      - ./compose/envs/kafka.env
    volumes:
      - kafka_data:/bitnami/kafka
    ports:
      - '9092:9092'
    networks:
      - ig_network
    restart: unless-stopped

  postgres:
    image: postgres:16.2-alpine
    container_name: ig_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./compose/envs/postgres.env
    ports:
      - '5432:5432'
    restart: unless-stopped

  # mongo:
  #   image: mongo:7.0
  #   container_name: ig_mongo
  #   env_file:
  #     - ./compose/envs/mongodb.env
  #   volumes:
  #     - mongo_data:/data/db
  #   ports:
  #     - '27017:27017'
  #   networks:
  #     - ig_network
  #   restart: unless-stopped

networks:
  ig_network:
    driver: bridge
